/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-ipc-types.mjs
 */

export interface AppInfo {
  name: string;
  version: string;
  identifier: string;
  platform: string;
}

export interface AppSettings {
  locale: string;
  launch_on_login: boolean;
  theme: string;
}

export interface SetSettingsInput {
  locale: string | null;
  launch_on_login: boolean | null;
  theme: string | null;
}

export const COMMAND_NAMES = [
  'ping',
  'get_app_info',
  'get_settings',
  'set_settings',
  'update_tray_title',
] as const;

export interface CommandArgs {
  ping: Record<string, never>;
  get_app_info: Record<string, never>;
  get_settings: Record<string, never>;
  set_settings: { input: SetSettingsInput };
  update_tray_title: { title: string };
}

export interface CommandReturns {
  ping: string;
  get_app_info: AppInfo;
  get_settings: AppSettings;
  set_settings: AppSettings;
  update_tray_title: void;
}

